"""add rubble_cost to orders

Revision ID: 24696593b758
Revises: 7b35fd11cbc8
Create Date: 2022-09-17 15:53:10.726763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24696593b758'
down_revision = '7b35fd11cbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rubble_cost', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'rubble_cost')
    # ### end Alembic commands ###
